### ISSUE TITLE
Permission Error on Start

### ISSUE THREAD

**Issue by Regnak85** [dulehuch/custombook-onjoin#1]
[19:23:43] [Server thread/ERROR]: Permission node 'cwboj.use' in plugin description file for CustomOnJoinBook v0.3 is invalid
java.lang.IllegalArgumentException: Data cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[cr.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.permissions.Permission.loadPermission(Permission.java:284) ~[cr.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.permissions.Permission.loadPermissions(Permission.java:233) [cr.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.plugin.PluginDescriptionFile.getPermissions(PluginDescriptionFile.java:764) [cr.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:370) [cr.jar:git-Spigot-9b8bba4-bdcc7c7]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [cr.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [cr.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [cr.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [cr.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [cr.jar:git-Spigot-9b8bba4-bdcc7c7]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [cr.jar:git-Spigot-9b8bba4-bdcc7c7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[19:23:43] [Server thread/INFO]: [CustomOnJoinBook] Enabling CustomOnJoinBook v0.3

**Comment by madtomic** [comment]
Please fix this!

**Comment by dulehuch** [comment]
Problem should be fixed now, I apologize for being absent for so long. Both the spigot thread and the source code have been updated.
